# apps/frontend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine  # En un caso real usarías tu imagen de frontend
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://backend-service:3000"